### ISSUE TITLE
Regarding doubtful case, need facility to highlight that particular word so that posteditor can look at it at the end of the set and also verifier can think of it while doing verification. E.g. peal or peel

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#107]
Regarding doubtful case, need facility to highlight that particular word so that posteditor can look at it at the end of the set and also verifier can think of it while doing verification. E.g. peal or peel

**Comment by akansharawat27** [comment]
There's an option to change the font color in the software. So, the user can use that to change the color of the doubtful words or phrases.
