### ISSUE TITLE
Set Corrupting issues

### ISSUE THREAD

**Issue by 0singh-ajit0** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#110]
- [x] Set is getting corrupted: All pages are getting filled by one sentence again and again
- [x] A non-breakable space is being introduced randomly
- [x] Some pages/part of pages are missing while pushing the set
- [x] HTML tags are being added while saving some pages
- [x] After adding horizontal line, words after it were getting erased

**Comment by akansharawat27** [comment]
For horizontal line issue, please refer to commit number d5945cd1a2abae43f100afd2b87f547705db9857. As for other points, we have implemented multithreading to the SaveFile function. Please refer to the commit number 7780eb4bca42b28b7f4a3aca0b873314c20c0969.
