### ISSUE TITLE
Changes in the Preview option

### ISSUE THREAD

**Issue by akansharawat27** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#115]
- [x] Add the Preview option for single-word replacement.
- [x] Reduce the length of sentences in the preview window.

**Comment by Misss-techy** [comment]
Added single replace for single word change in global replace. c7050eea1ba9b1ccf9d1bb246a01ddcc0e7a3a9d

**Comment by sujaytorvi** [comment]
We have completed the requirement and also shown the video of the same. It will be released soon.
