### ISSUE TITLE
Tool Should not crash on opening a malformed / corrupted project

### ISSUE THREAD

**Issue by sujaytorvi** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#117]
Whenever we open a project in our OCR Tool it gets crashed if the project xml file is malformed or the set files are corrupted. We need to show an appropriate message in case of project is malformed instead of crashing

**Comment by akansharawat27** [comment]
Please refer to the following commits: e8c1b750c7113d187307dff54e7c2aeef3031122, 2119838611c77aa5a69ee1fb9a0930503b6c2f16, and b904e973e2106c4d9ce3c4f8185e616ba38734b2.
