### ISSUE TITLE
Git error while opening 

### ISSUE THREAD

**Issue by duttaANI** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#122]
![Capture](https://user-images.githubusercontent.com/45551804/157424409-a769b022-b4e7-4241-89dd-45a79b5a5318.PNG)

Application log -

[application_log.txt](https://github.com/IITB-OpenOCRCorrect/iitb-openocr-digit-tool/files/8213847/application_log.txt)

**Comment by 0singh-ajit0** [comment]
Issue was in the path of gitconfig and gitattrib files. They were present in different folder. Instead they should be present in C:\Program Files\Git\etc OR C:\Program Files (x86)\Git\etc directories.
