### ISSUE TITLE
Optimize global-replace checkbox response.

### ISSUE THREAD

**Issue by Anjani9783** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#130]
- The global replacement window was hanging when the user tries to replace or upload more than fifty words. This was happening when the user clicks on the first checkbox.

**Comment by akansharawat27** [comment]
Please refer to commit number e06d1962abc4806f3765c7516ba5b5ab76be8cf6, 60521be4f6eda22e922897b9268c04192bfd6fbc and 32765beea103fab2433b438d942b4bbcf280d018.
