### ISSUE TITLE
Search Facility in Dictionary

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#131]
- Add a search bar in the dictionary window to search for words present in the dictionary.

**Comment by akansharawat27** [comment]
Please refer to the commit number 97096333bd59c4a03d999ddd9cb5cf5a303aff06, dd8a3d9ae240c3212811380f3f09253a40f8a79d and 7971039999cff7422e6e2421b3e5227bde121a8c.
