### ISSUE TITLE
Phrase level replacement is not working

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#137]
Set Name -: NGMA_5_1 
Link- https://github.com/UdaanContentForLogging/NGMA_5_1 (Shared with Sujay)
Phrase -  नंदलाल के रेखाचित्र और रेखाचित्र' changed to 'ड्राइंग्स एंड स्केचेस ऑफ़ नंदलाल' 
Page No-  24, 25 ,67 -111

**Comment by sujaytorvi** [comment]
Anjani I want this issue fixed urgently. Ajit And Sujay will assist.

**Comment by akansharawat27** [comment]
Please refer to the commit number 47dd1ad265e17a69c4ab0791d1610677a27f96c7.
