### ISSUE TITLE
scrolling-alternative

### ISSUE THREAD

**Issue by namratanwani** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#14]
- [x] While scrolling through an image just for editing, a single click on the image pops up a dialog box for image marking, even when image marking is not needed. Please add a specific button for image marking.

**Comment by AnujaDumada8** [comment]
1.Once the image part is zoomed in, the image part does not remain stable while moving the cursor.
2.while we single click on the image it continues showing add image table equation tab
![Screenshot_2](https://user-images.githubusercontent.com/74762590/129512559-2dcb2fb4-5013-4193-9235-3f38cccd6589.png)

**Comment by AnjaliVijayvargiya** [comment]
we added a button functionality for this. 
Resolved in v2.5.1
