### ISSUE TITLE
Changes in download PDF option 

### ISSUE THREAD

**Issue by akansharawat27** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#146]
- Add an option to see a page-level PDF preview.
- Add more settings for PDF customization such as margin, page size, orientation, etc.

**Comment by Anjani9783** [comment]
Please refer to the commit number 3c7a0071f1ec16f53941339a96ce449d5ccb84e1 and fd8d4cc5a694027e30b908d1f02a24c2e3c6e489
