### ISSUE TITLE
Features Required

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#170]
1. Add a checkbox option in the global replace preview button in which instance the user wants to change the word and will select the checkbox.  Screenshot - 
![image](https://user-images.githubusercontent.com/74762590/186600766-a7d9377e-9232-4b05-9fae-33a2863920d0.png)

2. Add Source text column in the global replace preview button |page | Source Sentence | Before Replacement | After Replacement |  Screenshot - 
![image](https://user-images.githubusercontent.com/74762590/186600902-88cf385d-c086-4bad-9514-68d3a41b96f9.png)

3. Highlight searched text in the dictionary searching option. Screenshot - 
![image](https://user-images.githubusercontent.com/74762590/186601673-e1eea269-a7f5-4983-99e1-dd39b24b74d6.png)

**Comment by Sadam452** [comment]
Refer to commit ce6b200a6451441d2b72bc844d215ab6e32f7e14 & 9b2a6602c97e13267265a3e95a0b72c3c1849c48
