### ISSUE TITLE
Search facility in dictionary

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#27]
- It is difficult to find words from the dictionary because too many words and words size is small, can you add search button for dictionary 
![image](https://user-images.githubusercontent.com/74762590/130895550-9e2c9136-96b6-49eb-bce9-caad1e4cfddc.png)
![image](https://user-images.githubusercontent.com/74762590/130895582-788f5c86-0b09-4534-a2c4-3f05012fdc01.png)

**Comment by akansharawat27** [comment]
For now, we have added a feature to highlight the words which are present in the dictionary. Thus the dictionary words are being highlighted in the HTML files. Please refer to commit number 95e1baac64b035825990cfb8ddd8f4109342e8c8 and d18e3676f886358398685d493943294d0b44fa35.
