### ISSUE TITLE
Replace edited words in subsequent pages

### ISSUE THREAD

**Issue by ayushbits** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#29]
User performs post-editing in our tool. If user has done some edit on the page, we'd like to perform this replacement over all subsequent pages.

After user presses Ctrl+S on the page, he should be shown an alert box 
`Do you want to replace x with y on all subsequent pages ?`
If user presses `yes` , then we will do the replacement else nothing.

**Comment by avisingh-git** [comment]
Added the said enhancement, also added multiple replacement with checkboxes so that the user can choose which words they would like to replace globally and which would like to stay the same. 58fed1363b2efbb53aee73b8682a02459351f183
