### ISSUE TITLE
Download as PDF button

### ISSUE THREAD

**Issue by ayushbits** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#35]
After completing the book our tool generate HTML and JSON file. Two options - 

- [x]  Add "download as PDF " button in the tool. 
- [x]  Export the post-edited document to a latex-compatible zip file

**Comment by avisingh-git** [comment]
Added a download as PDF option in the software. This will generate a PDF file of the correcter/verifier HTML pages in the currently working project with the name "Bookset.pdf", please refer to 06860dca759a78cbcdf7ed2ce1a28b1716f01f41

**Comment by Misss-techy** [comment]
The stand-alone python application which uses pandoc has been revised and now the tool is functional. Image capabilities has been added and now the generated latex files automatically contains images without any manual addition.
