### ISSUE TITLE
After Pushed Image,Equation,Table in git, another person unable to see the image

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#38]
After Pushed Image,Equation,Table in git, another person unable to see the  Image,Equation,Table 
![WhatsApp Image 2021-09-03 at 2 38 33 PM](https://user-images.githubusercontent.com/74762590/132011841-232e588a-2c46-4a56-bfd4-32fafbe43a49.jpeg)
![WhatsApp Image 2021-09-03 at 2 37 29 PM](https://user-images.githubusercontent.com/74762590/132011847-01b6602b-fcc9-406a-b673-f5ed72354c24.jpeg)

**Comment by avisingh-git** [comment]
We have updated the code to remove absolute path and adjusted it to point inside the Bookset the verifier/correcter is working on. Now the images will display on every system. Commit number: 05ba31785ab3d12e164d129366956337f0301e22
