### ISSUE TITLE
Page Change Shortcuts loose alignment of the new page

### ISSUE THREAD

**Issue by akansharawat27** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#39]
- [x]  When we navigate to the next/previous page using page change icon shortcuts or icon, if there is no opened tab next then it is opening the next page from the directory but the alignment of the new loaded page is lost.

**Comment by avisingh-git** [comment]
Solved the bug, now you can use the shortcuts and icon to shift pages easily. Please refer to 06860dca759a78cbcdf7ed2ce1a28b1716f01f41
