### ISSUE TITLE
Remove non-necessary initial from path

### ISSUE THREAD

**Issue by ayushbits** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#42]
Currently, tool shows many non-necessary text such as complete path of the corrector and verifier with the folders. In this case initials **CorrectorOutput/** or **VerifierOutput** aren't required.
Secondly, we need not show txt files in the folder.

![image](https://user-images.githubusercontent.com/30416518/132949713-95071257-11e7-4ec3-8191-a96eb337e12f.png)

**Comment by avisingh-git** [comment]
Added a directory structuring to the software which will help in easy navigation and access. Commit number: 74f38897a5c3b3386a4f0e9f0fedbd9e0187578c
![Screenshot from 2021-09-21 15-32-54](https://user-images.githubusercontent.com/55029562/134152184-09c0be89-85a0-4a04-bea2-caa1eba8fb29.png)
