### ISSUE TITLE
Cropped image is not loading

### ISSUE THREAD

**Issue by akansharawat27** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#43]
- [x] When we crop an image from the page opened in the application, the image part cropped is not loading in the current browser windows but it's saving in the cropped image folder.

**Comment by avisingh-git** [comment]
We have changed the image path to be loaded in the HTML, now you can successfully view the image. Commit number: 74f38897a5c3b3386a4f0e9f0fedbd9e0187578c
