### ISSUE TITLE
Disallow multiple tabs in the editor

### ISSUE THREAD

**Issue by ayushbits** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#46]
Currently when user open a page in the editor, it opens up in a new tab. This is causing problems for dict replacements and navigation. We need to disallow multiple tabs and allow only a single tab facility

**Comment by Misss-techy** [comment]
The software now doesn't support multiple tabs and only one editing window is shown. In accordance to this new feature, we have revised save, next page, previous page and tab selection features.  fba3d521804b9108def321b75574805907dee11d
