### ISSUE TITLE
After Globally replace Not all words are  changing

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#51]
@avisingh-git @akansharawat27 
I changed कंपनी into संगठन 
![image](https://user-images.githubusercontent.com/74762590/134651623-b8e33068-3eeb-4d06-ae39-c087bb372d9b.png)
but in the same document कंपनी word is not replaced.
![image](https://user-images.githubusercontent.com/74762590/134651895-7352ea55-b5ad-4566-ad62-9c1df1e0d08a.png)

**Comment by akansharawat27** [comment]
Resolved the issue by deleting .EditedFile.txt file every time when a tab is closed. Please refer to commit number 6116fb683ca8869162572f7dbf04244614aedff5 and ff4be1938edc16291d9d0f6d148f74d1ca66221a.
