### ISSUE TITLE
Add compare corrector or verifier output for all or multiple pages

### ISSUE THREAD

**Issue by akansharawat27** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#55]
- [ ] Currently, compare corrector output and compare verifier output does the comparison for a single page only. Now, we want to implement these features for all or multiple pages.

**Comment by Misss-techy** [comment]
The compare corrector output and compare verifier window now supports multiple page with a left and right navigation button. The window arrangements are changed and code has been revised.
