### ISSUE TITLE
Crop image feature should work for the zoomed image 

### ISSUE THREAD

**Issue by akansharawat27** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#63]
- [x] Currently, when we zoom on an image and try to crop it using the mark regions button, then the image cropping feature is not working properly. So, we need to make it possible to crop the zoomed image.

**Comment by sujaytorvi** [comment]
Refer Commit: 0b5db483378df2aa5b6b8d235d03f6a934fd70a3
