### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by akansharawat27** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#66]
- [x] Once we change the font and font size of the page and save it, then on reopening the same page again the font and font size of the dictionary words are changed back to the default font properties. The font properties should be the same for the entire page.

![image](https://user-images.githubusercontent.com/43927996/142979660-8a5145bf-b64a-4fc7-9d18-347e45686509.png)

**Comment by Misss-techy** [comment]
QTextCharFormat were overridden and the bug is resolved 4c37ea2ede5bf64bb86a7c8098666b6a1e958673
