### ISSUE TITLE
Changes in the UI of the software

### ISSUE THREAD

**Issue by akansharawat27** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#67]
- [x] Add more spacing in the menu bar options.
- [x] Add taskbar at the bottom which will show the word count of the HTML page.
- [x] Add an option to show recently opened projects.
- [x] Add loading screen or dialog box to show data is loading when we click on Load Data.
- [x] Disable the icons which are restricted to use.
- [x] Show only HTML files in the Project window.
- [x] Change in design and icons to give the software a modern look.

**Comment by sujaytorvi** [comment]
added loading window ....

**Comment by Amn04** [comment]
Added status bar to show word count in buttom of window

**Comment by Misss-techy** [comment]
Added recent project menu item a6f38516db661fbaf3852604eb4d1663aecae02b
