### ISSUE TITLE
Not able to see per page time in timelog.json file

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#72]
![image](https://user-images.githubusercontent.com/74762590/147037598-8a0cd5bd-f1e4-47de-be4f-b0ebfe2ee84d.png)
Not able to see per page time in timelog.json file

**Comment by AnujaDumada8** [comment]
@akansharawat27 @sujaytorvi 
Timelog file not updating....
![image](https://user-images.githubusercontent.com/74762590/148947791-9ba5404d-e4a7-4542-9fb3-4f665f9cedd1.png)

**Comment by shivang2121** [comment]
We tested the Timelog.json file and it is updating properly.
