### ISSUE TITLE
Add Vertical Line and Justified Alignment

### ISSUE THREAD

**Issue by akansharawat27** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#75]
- [ ] Add vertical line
- [x] Add justified alignment.

**Comment by akansharawat27** [comment]
Vertical line addition is not implementable in Qt as we have tried different approaches.

**Comment by shivang2121** [comment]
Vertical line cannot be done in QT. Justified alignment can be found on commit number 926cfa4ccaad7d33dba22cd594b0e612ad74db1a
