### ISSUE TITLE
 Regarding Global Replacement: Currently in the preview part, the source English sentence is not showing.

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#76]
Regarding Global Replacement: Currently in the preview part, the source English sentence is not showing. 
Gajananji suggestion  - should be shown also source part, if possible
![WhatsApp Image 2022-01-10 at 1 27 26 PM](https://user-images.githubusercontent.com/74762590/148742654-7eb0d362-c483-4aef-9945-fcc1472be411.jpeg)
. @akansharawat27 @sujaytorvi

**Comment by sujaytorvi** [comment]
Duplicate issue
