### ISSUE TITLE
font size of the preview sentences is very small

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#77]
![WhatsApp Image 2022-01-10 at 1 27 26 PM](https://user-images.githubusercontent.com/74762590/148742774-35e40f54-32dd-4046-8c9d-60a80c2aae5b.jpeg)
@sujaytorvi @akansharawat27

**Comment by Misss-techy** [comment]
Set font size to 14pt. It now appears larger.
