### ISSUE TITLE
V2.7.4  version tool crashing issue   Gajananji facing

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#78]

**Comment by AnujaDumada8** [comment]
https://user-images.githubusercontent.com/74762590/148758696-b7a068fd-430e-4b65-bd4d-4cd15b7d5043.mp4

**Comment by sujaytorvi** [comment]
@akansharawat27 @AnujaDumada8 This has been fixed. We'll soon release it and give it to gajanan ji for testing.

**Comment by akansharawat27** [comment]
Extra space was being added in the Cpair file which was causing the software to crash on clicking on LoadData. Please refer to commit number faf16d787aeb91550b88393ae6305292bd26bc90.
