### ISSUE TITLE
Conversion issue In globally replace log file 

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#79]
![WhatsApp Image 2022-01-05 at 4 55 41 PM](https://user-images.githubusercontent.com/74762590/148756949-5e38fe7c-3803-4aaa-bbaa-1b1a5d3201ff.jpeg)
![WhatsApp Image 2022-01-05 at 4 56 23 PM](https://user-images.githubusercontent.com/74762590/148756959-0f1dc1bb-b762-4c54-bdde-e0a8358a1b08.jpeg)

**Comment by shivang2121** [comment]
Please check for commit number 7d73d83b19e639ac17685aa56d5ebb1bf102f623
