### ISSUE TITLE
Zoom Slider and Scroll Bar Issue

### ISSUE THREAD

**Issue by akansharawat27** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#80]
- [x] After using the zoom slider multiple times in the software, the zoom in and zoom out don't work properly. 
- [x] Also, reduce the size of the scroll bar in the project window.

**Comment by sujaytorvi** [comment]
It is fixed now.

**Comment by akansharawat27** [comment]
Please refer to commit number 716e5fbc7b6b0c5cc3e8909b866cd7e738123bfe.

**Comment by akansharawat27** [comment]
The image is disappearing while zooming.

**Comment by akansharawat27** [comment]
Please refer to commit number a10923574487c0ac96a1fc21f53b398b7ce79fe4.
