### ISSUE TITLE
Can we automate such check while loading the dictionary which will allow the app to crash (or shutdown) gracefully. In cash of crash, such error logs can be generated which we can ask users to share with us

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#88]
Can we automate such a check while loading the dictionary which will allow the app to crash (or shutdown) gracefully? In case of a crash, such error logs can be generated which we can ask users to share with us

**Comment by sujaytorvi** [comment]
we have implemented it and will release in the upcoming build. 
![image](https://user-images.githubusercontent.com/53830055/149499751-daaf36d1-85e7-4119-bcb6-5a0cae00c31b.png)
Screenshot of the message shown. The log file is named as "application_logs.txt" and it is present in the same directory as the application qpadfinal.exe file.
