### ISSUE TITLE
Marking of Images tool issue

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#90]
Tool issue regarding Marked Images: Found that marked images in the pages are mixed. It is happened in the previous pages also. Sometimes also observed that after marking the images for current page, it is not matched with the source image.  Different image is displaying on the current page.

![image](https://user-images.githubusercontent.com/74762590/149716825-a4596245-e6db-4d70-b794-74f43fdb2bdd.png)
![image](https://user-images.githubusercontent.com/74762590/149716954-8b5ec9ef-7808-4422-8eac-7baac3c11267.png)

**Comment by akansharawat27** [comment]
Image.xml file was not generating correctly which was causing the incorrect loading of cropped images. The text files need to be there in the Inds folder and the image.xml file should not be there in the set folder by default. That file is auto-generated when the set is opened in the tool.
