### ISSUE TITLE
Global Replacement feature: Extra space

### ISSUE THREAD

**Issue by AnujaDumada8** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#91]
Tool Issue regarding Global Replacement feature: After using global replacement, the tool is adding an extra space before and after the replaced word. Total two extra spaces are adding.
It means unwanted Extra spaces are adding by the tool.

**Comment by akansharawat27** [comment]
@AnujaDumada8 Could you tell me which version you are facing this issue with?

**Comment by AnujaDumada8** [comment]
@akansharawat27 latest version 2.7.5  Gajanaji facing this issue

**Comment by akansharawat27** [comment]
Please refer to the commit number b19769f21d3045fb6ea2bb6db59909804183790b.
