### ISSUE TITLE
Book1 text to be replaced with project name

### ISSUE THREAD

**Issue by ayushbits** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#93]
Project Name should come instead of 'Book1' .  
![image](https://user-images.githubusercontent.com/30416518/149970382-cf3a7af3-04b0-4827-b1ce-4b0ea2e08818.png)

**Comment by akansharawat27** [comment]
We have passed the project directory name as a parameter to the Project tag in the project.xml file. So, when a project is opened the project directory name will be shown in place of Book1. For reference, please refer to commit number f4961918e1ca8b2b107f048538b0978ea4c95f04.
