### ISSUE TITLE
Tool crashing in latest version

### ISSUE THREAD

**Issue by ayushbits** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#97]
Clone pcray book from [here](https://github.com/UdaanContentForLogging/PCRayBook-Udaan) but tool crashing while opening. Tried [this also](https://github.com/UdaanContentForLogging/UnderstandingCombustion-Udaan) but same result.

![image](https://user-images.githubusercontent.com/30416518/150125613-dd0d3c5e-3fe4-4f23-be17-79490ecf3893.png)

**Comment by sujaytorvi** [comment]
Issue resolved.

Reason for crash:

The XML included files which were not available. However the tags were valid 

It included the git files. when we removed them, it got resolved

*Not caused due to a bug In the tool*
