### ISSUE TITLE
Changes in the Find and Replace option

### ISSUE THREAD

**Issue by akansharawat27** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#98]
- [x] Sometimes, the replace option is not working after navigating on words multiple files.
- [x] Change the color of the word when it is being navigated with find next or previous option.
- [x] Extend the feature of find to all the pages in the set.

**Comment by Misss-techy** [comment]
Extended the find feature to all pages(next and previous) and fixed the word color to blue.
b5abf288e12313ce569d341b110f96ac3699408d 10b16a007fb85beddf687c2789463346e4e4a401
